name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: >-
          cmake -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=install

      - name: Build
        run: cmake --build build -j 4

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Install
        run: cmake --install build
